# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20180127_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contracttemplate',
            options={'verbose_name': '合同模版'},
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='contract_agree',
            new_name='contract_agreed',
        ),
    ]
